---
title: "Polars package examples"
format: gfm
toc: true
warning: false
---



\newpage 



## install package 

```{r}
#| eval: false
Sys.setenv(NOT_CRAN = "true")
install.packages("polars", repos = "https://community.r-multiverse.org")
```



## get start

```{r}

library(polars)
df <- pl$DataFrame(
    x = 1:5,
    y = 10:14,
    z = 5:1
)
df
```




```{r}

df$mean()
df$sum()
df$select('x', 'y')$mean()
# help(package = 'polars')

## select 
df$ 
select('z')$
mean()

## filter
df$
filter(pl$col('x') > 2)
```


## groupby and aggregate


```{r}
dat = pl$DataFrame(iris)
dat$group_by('Species')$
agg(
    mean_Peta_width = pl$col('Petal.Width')$mean(), 
    sum_Sepal_Width = pl$col("Sepal.Width")$sum()
)
```



## mutate


```{r}
dat <- pl$DataFrame(
    Id = 1:10, 
    x1 = rnorm(10) |> round(2), 
    x2 = rgamma(10, 2, 2) |> round(2), 
    x3 = rbinom(10, size = 5, prob = 0.4)
)

dat2 = dat$with_columns(
    val1 = pl$when(pl$col('x1') > 1)
    $then(1)
    $otherwise(-1)
)

```


## inexing 


```{r}
dat2[1, 2]
dat2[1, 1:2]
dat2[-1, 1:2]
```



## generate a sample data 

```{r}
set.seed(1234)
datt <- pl$DataFrame(
    x1 = rnorm(5e+7, 2, 1), 
    x2 = rgamma(5e+7, 2, 2), 
    x3 = rbinom(5e+7, 15, 0.6), 
    x4 = rnorm(5e+7, 5, 2), 
    x5 = rnorm(5e+7, -10, 3), 
    x6 = rnorm(5e+7, -20, 2), 
    x7 = rgamma(5e+7, 5, 3), 
    x8 = rexp(5e+7, rate = 1/4), 
    x9 = rnorm(5e+7, -7, 2)
)


datt$write_csv("Data_samp.csv")


```

## compare with data.table


```{r}
rm(list = ls())

## data.table section get elapsed time for read and run function along columns
library(data.table)

start_time1 <- Sys.time();
dat1 <- fread('Data_samp.csv', header = T);
dat1[, lapply(.SD, mean)];
end_time1 <- Sys.time();
(Diff_time_data_table <- difftime(end_time1, 
            start_time1, units = "secs"))



```


***
***

```{r}
rm(list = ls())
## polars section get elapsed time for read and run function along columns
start_time2 <- Sys.time();
dat2 <- pl$read_csv('Data_samp.csv');
dat2$mean()
end_time2 <- Sys.time();
(Diff_time_polars <- difftime(end_time2, 
            start_time2, units = "secs"))
```