---
title: "OutPut_temp"
author: Generated by BlueSky Statistics, LLC
date: "Sat Jul 29 2023 5:23:25 AM" 
output:
  html_document: default
BlueSkyStatistics Version: 10.3.2
---


```{r setup-libraries, echo= FALSE, eval= TRUE, include = FALSE}
library(plyr)
library(dplyr)
library(rmarkdown) 
library(kableExtra)
library(BlueSky)
library(gdata)
library(stringr)
library(openxlsx)
library(haven)
library(readr)
library(readxl)
library(data.table)
library(foreign)



# The folowing is needed if R Studio needs to Knit to PDF
#library(tinytex)
```

```{r setup-knitr-options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)

# Will keep the one single global graphics device open for all the code chunks 
#knitr::opts_knit$set(global.device = TRUE)

# Will output all the graphics - otherwise only the last graphics will be shown
knitr::opts_knit$set(fig.keep = 'all')

# To see the fully rendered output not the markup
knitr::opts_chunk$set(results='asis')

# Comment the above and un-comment the below to see the non rendered markup output
#knitr::opts_chunk$set(results="markup")
```

```{r BSky-config, eval= TRUE, include = FALSE}
        
#To flush internally all previously run BSkyFormat() output 
BSkyGetHoldFormatObjList()

# Sets up the default output styling parameters 
# BSky.print.text('rst')
BSky.print.html()
# BSky.print.text('rprint')

# Output Data cell - decimal points/engineering notation settings
#BSkySetDecimalDigitSetting(2)
#BSkySetEngNotationSetting(TRUE)
#BSkySetRound(TRUE)
#BSkySetPvalueDisplaySetting(FALSE)

# End of config set up 
```
# Open Dataset: Spss_data_sample

```{r}
BSkyloadDataset(fullpathfilename='E:/University_projects/Projects/habib_ezatabadi/Blue_SKy_Project/sample_data/Spss_data_sample.sav', filetype='SPSS', worksheetName=NULL, replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', encoding=NULL, datasetName='Spss_data_sample')
BSkyLoadRefresh("Spss_data_sample")
```
# Custom R Code

```{r}

BSkyResults <-BSky_Shapiro_Wilk_normality_test(vars = c('y'), dataset=c('Spss_data_sample'))
BSkyFormat(BSkyResults)
#remove (BSkyResults)

```
# Custom R Code

```{r}

Spss_data_sample %>%
dplyr::select(y) %>%
    BSky_Shapiro_Wilk_normality_test() %>%
    BSkyFormat()

```
# Fit of univariate distributions to non-censored data

```{r}
require(fitdistrplus)
gofstat_format <- function(dist_test_list = list(), fitname_list = c()) {
	if(length(dist_test_list) > 0){
		gofstat_comp = gofstat(dist_test_list, fitnames = fitname_list)
		if(!is.null(gofstat_comp$ks)){
			gofstat_comp_stat = rbind(gofstat_comp$ks, gofstat_comp$cvm, gofstat_comp$ad)
			row.names(gofstat_comp_stat) = c("Kolmogorov-Smirnov", "Cramer-von Mises", "Anderson-Darling")
			BSkyFormat(gofstat_comp_stat, outputTableRenames="Goodness-of-fit statistics")
		}
		gofstat_comp_criterion = rbind(gofstat_comp$aic, gofstat_comp$bic)
		row.names(gofstat_comp_criterion) = c("Akaike's Information Criterion (AIC)", "Bayesian Information Criterion (BIC)")
		BSkyFormat(gofstat_comp_criterion, outputTableRenames="Goodness-of-fit criteria")
		
		BSkyFormat(gofstat_comp, outputTableRenames=c("Goodness-of-fit: Details"))	
	}
}

	
dist_test_comp_list = list()
dist_test_comp_legendtext = c()

 
	fitg_norm = NULL
			suppressWarnings(
			fitg_norm <- fitdistrplus::fitdist(data = as.numeric(Spss_data_sample$y), 
							distr = "norm",
							method = 'mle',
							keepdata = TRUE
							)
		)
		
	if(!is.null(fitg_norm)) {
		dist_test_comp_list = c(dist_test_comp_list, list(fitg_norm))
		dist_test_comp_legendtext = c(dist_test_comp_legendtext, "normal")
		
		filter_empty_rows = BSkyFormat2(fitg_norm)$tables[[1]]
		filter_empty_rows = filter_empty_rows[filter_empty_rows[,2]!="",]
		# BSkyFormat(filter_empty_rows, 
		# 				outputTableRenames = paste("Summary: normal distribution fit test for y"))
	 	knitr :: kable(filter_empty_rows, 
		caption = "Summary: normal distribution fit test for y", align = "c")
		gofstat_format(dist_test_list = fitg_norm, fitname_list = c("normal"))
		plot(fitg_norm, demp = TRUE)
		cdfcomp(fitg_norm, addlegend=TRUE)
		denscomp(fitg_norm, addlegend=TRUE)
		ppcomp(fitg_norm, addlegend=TRUE)
		qqcomp(fitg_norm, addlegend=TRUE)
	}





	
	
	
	
	
	

if(length(dist_test_comp_list) > 1){
	BSkyFormat("Comparison of the distribution fits")
	
	gofstat_format(dist_test_list = dist_test_comp_list, fitname_list = dist_test_comp_legendtext)
	
	cdfcomp(dist_test_comp_list, legendtext=dist_test_comp_legendtext)
	denscomp(dist_test_comp_list, legendtext=dist_test_comp_legendtext)
	qqcomp(dist_test_comp_list, legendtext=dist_test_comp_legendtext)
	ppcomp(dist_test_comp_list, legendtext=dist_test_comp_legendtext)
}
			

```
